"""change to store attachments in db

Revision ID: 274c931b2bab
Revises: 76204e77215b
Create Date: 2025-09-28 16:46:13.352493

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '274c931b2bab'
down_revision = '76204e77215b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('attachments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('filename', sa.String(length=255), nullable=False))
        batch_op.add_column(sa.Column('content', sa.LargeBinary(), nullable=False))
        batch_op.drop_column('file_path')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('attachments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('file_path', sa.VARCHAR(length=500), autoincrement=False, nullable=False))
        batch_op.drop_column('content')
        batch_op.drop_column('filename')

    # ### end Alembic commands ###
