"""added enum to user role

Revision ID: 2a5356006fdb
Revises: 11580043e5f4
Create Date: 2025-09-26 12:21:14.399931

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2a5356006fdb'
down_revision = '11580043e5f4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('role',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.Enum('STAFF', 'MANAGER', 'DIRECTOR', 'HR', name='userrole', native_enum=False),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('role',
               existing_type=sa.Enum('STAFF', 'MANAGER', 'DIRECTOR', 'HR', name='userrole', native_enum=False),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)

    # ### end Alembic commands ###
